message = "Hello World"
print(message)
"""
capitalize(self, /) -- 
casefold(self, /)
center(self, width, fillchar=' ', /)
count(...)
encode(self, /, encoding='utf-8', errors='strict')
endswith(...)
expandtabs(self, /, tabsize=8)
find(...)
format(...)
format_map(...)
index(...)
join(self, iterable, /)
ljust(self, width, fillchar=' ', /)
lower(self, /)
lstrip(self, chars=None, /)
partition(self, sep, /)
replace(self, old, new, count=-1, /)
rfind(...)
rindex(...)
rjust(self, width, fillchar=' ', /)
rpartition(self, sep, /)
rsplit(self, /, sep=None, maxsplit=-1)
rstrip(self, chars=None, /)
split(self, /, sep=None, maxsplit=-1)
splitlines(self, /, keepends=False)
startswith(...)
strip(self, chars=None, /)
swapcase(self, /)
title(self, /)
translate(self, table, /)
upper(self, /)
zfill(self, width, /)
maketrans(...)
"""

"""
isalnum(self, /)
isalpha(self, /)
isascii(self, /)
isdecimal(self, /)
isdigit(self, /)
isidentifier(self, /)
islower(self, /)
isnumeric(self, /)
isprintable(self, /)
isspace(self, /)
istitle(self, /)
isupper(self, /)
"""
print(message.lower())
print(message.islower())